[package]
name    = "tomlpp"
version = "0.6.0"
description = "tomlpp is a c++17 header-only library for parsing TOML forked cpptoml and can use orm and std::optional"
git = "https://github.com/injae/cpptoml.git"

[lib]
name   = "tomlpp"
type   = "header-only"

[dev-dependencies]
Catch2="2.9.1"

[[test]]
    name="parse_test"
    source= ["test/test.cpp"]